import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/portfolio.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import Experience from "@/components/Experience";
import Education from "@/components/Education";
import Skills from "@/components/Skills";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center justify-end w-full min-h-screen">
        <Layout className="pt-0">
          <div className="grid grid-cols-2 items-center justify-between w-full">
            <div className="w-10/12">
              <Image
                src={profilePic}
                alt="ProfilePic"
                className="w-full h-auto "
              />
              {/* <span class="circle-spin"></span> */}
            </div>
            <div className="flex flex-col items-center self-center">
              <AnimatedText
                text="Hi, My name is Mahapra Naim"
                className="!text-6xl !text-left"
              />
              <p className="my-4 text-base font-medium">
                I’m a motivated and dedicated individual With a B.Sc. degree in
                Computer Science & Engineering from the Military Institute of
                Science & Technology. Explore my latest projects, showcasing my
                expertise in web development, UI/UX designing etc.
              </p>
              <div className="flex items-center self-start mt-2">
                <Link
                  href="/MahaparaNaim.pdf"
                  target={"_blank"}
                  className="flex items-center bg-darkPink text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-darkPink border border-solid border-transparent hover:border-darkPink"
                  //download={true}
                >
                  Resume <LinkArrow className={"w-6 ml-2 mb-1"} />
                </Link>
                <Link
                  href="mahaparanaim57@gmail.com"
                  target={"_blank"}
                  className="ml-4 text-lg font-medium capitalize text-darkPink underline"
                >
                  {" "}
                  Contact Now{" "}
                </Link>
              </div>
            </div>
          </div>

          {/* <Skills />
          <Experience />
          <Education /> */}
        </Layout>
        <HireMe />
      </main>
    </>
  );
}
